name: publish-godel-artifacts
on:
  push:
    tags:
      - /^v?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?$/
jobs:
  run-godel-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.godel
          key: ${{ runner.os }}-godel-${{ hashFiles('godelw', 'godel/config/godel.yml') }}
      - run: ./godelw dist
        env:
          GOPATH: "/home/runner/go"
      - run: ./godelw publish github --add-v-prefix --api-url=$GITHUB_API_URL --user=palantir --repository=godel --token=${{ secrets.GITHUB_TOKEN }}
        env:
          GOPATH: "/home/runner/go"
